### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by meerpaluten** [Limework/RedisBungee#1]
i have this error since some times:
13:23:35 [SEVERE] [RedisBungee] proxy-1_ZPu1cV is 15971 seconds behind! (Time not synchronized or server down?)
the server is offline and i will that it is offline

**Comment by Govindass** [comment]
what do you mean by "the server is offline and i will that it is offline"?

**Comment by meerpaluten** [comment]
i have turn off the server, but the error come too

**Comment by Govindass** [comment]
have you turned off the server nicely, with "end" command?

**Comment by meerpaluten** [comment]
No, I think the server was frozen and I terminated it

**Comment by Govindass** [comment]
in that case it is normal, you need to stop it nicely in order to not have these warnings

**Comment by meerpaluten** [comment]
The problem is that I am using Redis with a cloud and I can't recreate the serverid

**Comment by Govindass** [comment]
I see, let's see what @ham1255 thinks about this

**Comment by ham1255** [comment]
Never seen this error before, make sure your system time is right + and shutdown every bungee cord nicely

**Comment by ham1255** [comment]
and also you could ignore this since this isn't harmful i think btw will check code if there some changes needed.

**Comment by mattmalec** [comment]
I've seen this before with my Kubernetes infrastructure. It occurs when RedisBungee doesn't have the chance to remove itself from the "heartbeats" key in the Redis server (i.e. not safely shutting down the server, a SIGKILL, etc.)

A heartbeat object is JSON formatted and looks like:
`{
  "server-id-1": "last-heartbeat-time",
  "server-id-2": "last-heartbeat-time",
  "server-id-3": "last-heartbeat-time"
}` 
and etc.

You could fix this by either removing the key of the offending server from that object or by completely deleting the heartbeats key from Redis. You should restart all your proxies for data consistency if you remove the heartbeat key entirely, but it's not necessary if you remove the offending server from the object.

As a more permanent fix, a config option that removes any server that have missed the heartbeat after X amount of seconds would be nice to see. Let me know if you'd like me to PR that addition.

Hope this helps. Thanks!

**Comment by ham1255** [comment]
Thanks for info!

**Comment by ham1255** [comment]
> I've seen this before with my Kubernetes infrastructure. It occurs when RedisBungee doesn't have the chance to remove itself from the "heartbeats" key in the Redis server (i.e. not safely shutting down the server, a SIGKILL, etc.)
> 
> 
> 
> A heartbeat object is JSON formatted and looks like:
> 
> `{
> 
>   "server-id-1": "last-heartbeat-time",
> 
>   "server-id-2": "last-heartbeat-time",
> 
>   "server-id-3": "last-heartbeat-time"
> 
> }` 
> 
> and etc.
> 
> 
> 
> You could fix this by either removing the key of the offending server from that object or by completely deleting the heartbeats key from Redis. You should restart all your proxies for data consistency if you remove the heartbeat key entirely, but it's not necessary if you remove the offending server from the object.
> 
> 
> 
> As a more permanent fix, a config option that removes any server that have missed the heartbeat after X amount of seconds would be nice to see. Let me know if you'd like me to PR that addition.
> 
> 
> 
> Hope this helps. Thanks!

But this kind of thing is harmless but if it causing issues please tell me!

**Comment by ham1255** [comment]
And also when that error happens what i can do is delete the server

**Comment by mattmalec** [comment]
It updates the heartbeat every 3 seconds to ensure the Redis server hasn't just randomly died. If its unable to update the heartbeat, it could be that a server has lost its connection to Redis, or simply that it wasn't shutdown safely.

**Comment by ham1255** [comment]
i made pull request try it 
#2
