### ISSUE TITLE
Player count not updating after a reboot

### ISSUE THREAD

**Issue by funnycubeguy** [Limework/RedisBungee#109]
### intended behavior

Player counts should sync and be the same.

### what the behavior you actually saw

Player counts after a reboot are not the same on one proxy.

### Steps to reproduce

Setup 2 velocity proxies with 1 server on each.
Players join both.
Reboot 1 of the proxies.
The proxy that wasn't rebooted keeps the proper player count while the proxy rebooted doesn't show the players on the other proxy.

### Velocity or Bungeecord Versions

Get Velocity 3.3.0-SNAPSHOT #400

### RedisBungee Version & Redis Version

ValioBungee 0.12.4

### Other

![Screenshot from 2024-06-23 02-09-57](https://github.com/ProxioDev/ValioBungee/assets/9994438/83da3db5-d37f-4a01-b3df-2ffac1fd3ac0)

**Comment by ham1255** [comment]
sorry for late response since 0.12 redisbungee there new setting called network id you need to make sure its same on both proxies

**Comment by alaajel** [comment]
What does `/rb show` outputs?

**Comment by funnycubeguy** [comment]
> /rb show

![image](https://github.com/user-attachments/assets/c9cf9f37-d9ea-4cee-9ad4-0b47b55b832c)
