### ISSUE TITLE
The Redis-Bungee Papi Expansion isn't loading.. on newer versions of papi 

### ISSUE THREAD

**Issue by ArjanSchoorl** [Limework/RedisBungee#11]
The redisbungee original placeholders don't work.

**To Reproduce**
1. Download placeholderapi
2. Setup redisbungee from limework
3. Do /papi ecloud download RedisBungee and /papi reload
4. See error in console `[PlaceholderAPI] redisbungee is attempting to register placeholders via a PlaceholderHook class which is no longer supported!`

**Expected behavior**
Show the playercount from all the proxies.

**Screenshots**
https://file.coffee/u/K36GD11iVvl4Ro.png ​

**Redis version? it should be at least 6 and above.**
6.0.5

**Bungeecord version or (the bungee fork name eg: waterfall) and your plugins**
 Waterfall
 https://file.coffee/u/tZhukz3SX9ElTr.png ​

**console logs?**
please provide any errors if there any.

**Comment by ham1255** [comment]
Hello there, i made pull request on that papi addon and simply it was ignored what you can do is download the source code and compile it here is the pull request https://github.com/PlaceholderAPI/RedisBungee-Expansion/pull/2

**Comment by ham1255** [comment]
After some thinking i think we should include papi addon too in source code as patches

**Comment by ArjanSchoorl** [comment]
> After some thinking i think we should include papi addon too in source code as patches

That is a good idea!

**Comment by ham1255** [comment]
okay as of now pr was merged! i am closing this
