### ISSUE TITLE
RedisBungeeAPI getServerToPlayers() method shadow relocate problem

### ISSUE THREAD

**Issue by Ayouuuu** [Limework/RedisBungee#112]
### intended behavior

getServerToPlayers()

### what the behavior you actually saw

```java
java.lang.NoSuchMethodError: 'com.google.common.collect.Multimap com.imaginarycode.minecraft.redisbungee.AbstractRedisBungeeAPI.getServerToPlayers()'
```

### Steps to reproduce

```java
java.lang.NoSuchMethodError: 'com.google.common.collect.Multimap com.imaginarycode.minecraft.redisbungee.AbstractRedisBungeeAPI.getServerToPlayers()'
```

### Velocity or Bungeecord Versions

https://api.papermc.io/v2/projects/waterfall/versions/1.21/builds/579/downloads/waterfall-1.21-579.jar

### RedisBungee Version & Redis Version

RedisVersion: 7.2
RedisBungee Version: 0.12.4

### Other

```pom
<dependency>
	<groupId>com.github.ProxioDev.ValioBungee</groupId>
	<artifactId>RedisBungee-API</artifactId>
	<version>0.12.4</version>
</dependency>
```
[MultiMap and ImmutableSet](https://github.com/ProxioDev/ValioBungee/blob/main/api/src/main/java/com/imaginarycode/minecraft/redisbungee/AbstractRedisBungeeAPI.java#L13-L14)
[relocate](https://github.com/ProxioDev/ValioBungee/blob/main/proxies/bungeecord/build.gradle.kts#L55)

**Comment by alaajel** [comment]
oops this documentation issue

https://github.com/ProxioDev/ValioBungee/wiki/API#relocation--access-built-in-unifiedjedis

read how to add relocations then add relocations of the lib you want to use
