### ISSUE TITLE
If login event was cancelled but redis bungee will see it as not cancelled

### ISSUE THREAD

**Issue by licen150** [Limework/RedisBungee#12]
Hello, im using Litebans plugin on bungee. If banned tried to connect to server he makes +1 to server online for 1+ min. Im using Bungeecord BotFilter. Latest RedisBungee build and Reds 6.2.4. 
![image](https://user-images.githubusercontent.com/38755713/124105908-5b6b1680-da6c-11eb-8314-a5da3c4710b8.png)

**Comment by ham1255** [comment]
so after further testing.... it seems does not even know if the event was cancelled. due being async which bad 
i am thinking moving to postlogin should better.

**Comment by ham1255** [comment]
try out this build. https://github.com/Limework/RedisBungee/suites/3298035448/artifacts/77054655
