### ISSUE TITLE
"Unsupported Redis version detected"

### ISSUE THREAD

**Issue by Xeravax** [Limework/RedisBungee#120]
### intended behavior

Valio to connect with my Redis server

### what the behavior you actually saw

Valio reports "Caused by: java.lang.RuntimeException: Unsupported Redis version detected"

### Steps to reproduce

No replication availible

### Velocity or Bungeecord Versions

Velocity 3.3.0-SNAPSHOT (git-6100e675-b416)
Copyright 2018-2023 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
velocitypowered.com - GitHub

### RedisBungee Version & Redis Version

Redis Version: Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6
RedisBungee Version: 0.12.4 (Latest release)

### Other

I am interested to know what version I exactly need.

**Comment by alaajel** [comment]
You need redis 6.2 or above
https://github.com/ProxioDev/ValioBungee/wiki/Installation#supported-redis-versions

**Comment by Xeravax** [comment]
Thanks, that solved the issue!
