### ISSUE TITLE
Player count synchronization failing

### ISSUE THREAD

**Issue by BeilorDA** [Limework/RedisBungee#121]
### intended behavior

Expect that from 2 proxy servers the number of players would be the total of the two proxies together

### what the behavior you actually saw

The first time I connected it through RedisBungee it was displayed correctly, but after simply restarting one of the proxies the number of players connected to the two servers was not displayed correctly.

What it showed was that on one server it showed the players that were only connected to that server and on the other proxy it showed all the players from the 2 proxies. What I am looking for is that the same number of connected players is shown on the 2 proxies (The ones from the 2 proxies together)

### Steps to reproduce

https://imgur.com/a/DFLWWlw
In the video you can clearly see that someone was already connected to Proxy-2 and no one appeared connected to Proxy-1.

But when connecting to Proxy-1, the players from the same individual server were counted, but Proxy-2 did count the players from Proxy-1 and Proxy-2.

### Velocity or Bungeecord Versions

XCord v1.61B-SNAPSHOT

### RedisBungee Version & Redis Version

RedisBungee version: 0.12.5
Redis server version: 7.4.0

### Other

I would like to receive a solution as soon as possible. Thank you.

**Comment by alaajel** [comment]
Can you run "/rb show" on proxies console? Screenshot output please at least 2 proxies

**Comment by the-w41k3r** [comment]
@ham1255 

![image](https://github.com/user-attachments/assets/1c1ac1eb-5a98-462e-b65d-1393214724c6)


![image](https://github.com/user-attachments/assets/9504db84-22e4-452e-9af4-5bdaa413a4ea)
![image](https://github.com/user-attachments/assets/6439b6f7-15c2-4a35-8739-1ea19033a955)




# Scarp all that. 
The problem was needed to set `handle-motd: true`

**Comment by alaajel** [comment]
lmao anyways good to know.
