### ISSUE TITLE
API breaking change: Change from JedisPool to Pool<Jedis>

### ISSUE THREAD

**Issue by Simonsator** [Limework/RedisBungee#14]
The api is getting broken by the update of version 0.7, as the method RedisBungee.getPool() does not return anymore JedisPool, but Pool<Jedis> now. Every plugin which uses the Pool from redisbungee is now broken due to this change, like my plugin party and friends. Please change it back to JedisPool, to allow developers to keep compatibility with the original redisbungee and this modified version.

**Comment by ham1255** [comment]
Actully this wasnt intended since Jedis pool is extended from pool<jedis>

**Comment by ham1255** [comment]
And also can you send any error fron the console

**Comment by ham1255** [comment]
And also revert back version 6.* for now till i find a fix

**Comment by Simonsator** [comment]
The error is:
`java.lang.NoSuchMethodError: com.imaginarycode.minecraft.redisbungee.RedisBungee.getPool()Lcom/imaginarycode/minecraft/redisbungee/internal/jedis/JedisPool;`

I already told the user for now to revert back to 0.6.3.

**Comment by ham1255** [comment]
Okay this worse it breaks most simple plugis too

**Comment by ham1255** [comment]
i will count this as intended since i said 0.6 will be maintained but 0.7 i will be differnet version of redis bungee which might have  breaking api stuff.

**Comment by ham1255** [comment]
i recommend using 0.6.3 for now.

**Comment by Simonsator** [comment]
Could you add to the 0.7 version a big red message that it is breaking api stuff? I had multiple people message me about this. As there are many forks of redisbungee which are using the old api I am not going to be able to change my plugin and keep compatibility with the original redisbungee and other forks.

**Comment by ham1255** [comment]
added warning into readme.
