### ISSUE TITLE
RedisBungee help

### ISSUE THREAD

**Issue by MasterGabeMOD** [Limework/RedisBungee#6]
Hi, 

Maybe I can get some help here with an unknown issue that I'm having. 

Basically, I'm having an issue with RedisBungee not keeping data in sync. Plugins that I have used with Redis support are not communicating, and I'm seeing weird issues where player counts never change. 

I also get a warning pop up that occurs:

**[RedisBungee]: Player is on the proxy but not in Redis.**

RedisBungee successfully connects with Redis without an issue. 

I'm having another issue where placeholderapi will not communicate using specific placeholders %redisbungee_Vanilla%

However when I change the placeholders back to %bungee_Vanilla%, it tries to gather data from a single instance but it never properly works. I've also tried using Holographic Displays with Redis support and it also can't communicate. 

Firewalls are completely disabled while testing. I've also removed all bungee plugins for testing as well. 

I'm running Travertine version git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:2ddf5d1:186

Any help appreciated.

**Comment by ham1255** [comment]
hi placeholder issue is known + can you give us info or logs when player is oon the proxy but not redis?

**Comment by MasterGabeMOD** [comment]
Yep, this was exactly the problem. I didn't have a password set for Redis. Thank you for your help!

**Comment by ham1255** [comment]
If problem still happens feel free to reopen the issue!

**Comment by ham1255** [comment]
Placeholder api problem has been fixed will be releasing 0.6.3 shortly

**Comment by ham1255** [comment]
![image](https://user-images.githubusercontent.com/34905970/119061710-115f3180-b9e6-11eb-9dae-d28e4f203867.png)
